site_name: ProLUG Course Books
site_url: http://professionallinuxusersgroup.github.io/course-books
repo_name: ProLUG Course Books
repo_url: https://github.com/ProfessionalLinuxUsersGroup/course-books
edit_uri: edit/main/docs
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.indexes
    - navigation.top
    - navigation.path
    - navigation.tabs
    - navigation.footer
    - toc.follow
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select

nav:
  - Home:
    - index.md
    - beginners/bsh.md
    -  certify.md
    - Contributing to ProLUG MkDocs:
      - contributing.md
      - development.md
  - Linux Admin Course:
    - Course Overview:
      - Syllabus: lac/syllabus.md
      - Course Project: lac/project.md
      - Table of Contents: lac/unitindex.md
    - Unit 1 - Linux File Operations:
      - Intro: lac/u1intro.md
      - Worksheet: lac/u1ws.md
      - Lab: lac/u1lab.md
      - Bonus: lac/u1b.md
    - Unit 2 - Essential Tools:
      - Intro: lac/u2intro.md
      - Worksheet: lac/u2ws.md
      - Lab: lac/u2lab.md
    - Unit 3 - Storage:
      - Intro: lac/u3intro.md
      - Worksheet: lac/u3ws.md
      - Lab: lac/u3lab.md
      - Bonus: lac/u3b.md
    - Unit 4 - Operating Running Systems:
      - Intro: lac/u4intro.md
      - Worksheet: lac/u4ws.md
      - Lab: lac/u4lab.md
    - Unit 5 - Managing Users and Groups:
      - Intro: lac/u5intro.md
      - Worksheet: lac/u5ws.md
      - Lab: lac/u5lab.md
    - Unit 6 - Firewalls:
      - Intro: lac/u6intro.md
      - Worksheet: lac/u6ws.md
      - Lab: lac/u6lab.md
    - Unit 7 - Package Management && Patching:
      - Intro: lac/u7intro.md
      - Worksheet: lac/u7ws.md
      - Lab: lac/u7lab.md
      - Bonus: lac/u7b.md
    - Unit 8 - Scripting:
      - Intro: lac/u8intro.md
      - Worksheet: lac/u8ws.md
      - Lab: lac/u8lab.md
      - Bonus: lac/u8b.md
    - Unit 9 - Containerization on Linux:
      - Intro: lac/u9intro.md
      - Worksheet: lac/u9ws.md
      - Lab: lac/u9lab.md
    - Unit 10 - Kubernetes:
      - Intro: lac/u10intro.md
      - Worksheet: lac/u10ws.md
      - Lab: lac/u10lab.md
      - Bonus: lac/u10b.md
    - Unit 11 - Monitoring:
      - Intro: lac/u11intro.md
      - Worksheet: lac/u11ws.md
      - Lab: lac/u11lab.md
    - Unit 12 - Baselines && Benchmarks:
      - Intro: lac/u12intro.md
      - Worksheet: lac/u12ws.md
      - Lab: lac/u12lab.md
    - Unit 13 - System Hardening:
      - Intro: lac/u13intro.md
      - Worksheet: lac/u13ws.md
      - Lab: lac/u13lab.md
      - Bonus: lac/u13b.md
    - Unit 14 - Ansible Automation:
      - Intro: lac/u14intro.md
      - Worksheet: lac/u14ws.md
      - Lab: lac/u14lab.md
    - Unit 15 - Troubleshooting:
      - Intro: lac/u15intro.md
      - Worksheet: lac/u15ws.md
      - Lab: lac/u15lab.md
    - Unit 16 - Incident Response:
      - Intro: lac/u16intro.md
      - Worksheet: lac/u16ws.md
      - Lab: lac/u16lab.md
    - Course Resources:
      - External Resources: lac/resources.md
      - Downloads: lac/downloads.md

  - Linux Security Course:
    - Course Overview:
      - Syllabus: psc/syllabus.md
      - Course Project: psc/project.md
      - Table of Contents: psc/unitindex.md
    - Unit 1 - Build Standards and Compliance:
      - Intro: psc/u1intro.md
      - Worksheet: psc/u1ws.md
      - Lab: psc/u1lab.md
    - Unit 2 - Securing the Network:
      - Intro: psc/u2intro.md
      - Worksheet: psc/u2ws.md
      - Lab: psc/u2lab.md
    - Unit 3 - User Access and System Integration:
      - Intro: psc/u3intro.md
      - Worksheet: psc/u3ws.md
      - Lab: psc/u3lab.md
      # - Bonus: psc/u3b.md
    - Unit 4 - Bastion Hosts and Airgaps:
      - Intro: psc/u4intro.md
      - Worksheet: psc/u4ws.md
      - Lab: psc/u4lab.md
    - Unit 5 - Updating Systems and Patch Cycles:
      - Intro: psc/u5intro.md
      - Worksheet: psc/u5ws.md
      - Lab: psc/u5lab.md
    - Unit 6 - Monitoring and Parsing Logs:
      - Intro: psc/u6intro.md
      - Worksheet: psc/u6ws.md
      - Lab: psc/u6lab.md
    - Unit 7 - Monitoring and Alerting:
      - Intro: psc/u7intro.md
      - Worksheet: psc/u7ws.md
      - Lab: psc/u7lab.md
      # - Bonus: psc/u7b.md
    - Unit 8 - Configuration Drift and Remediation:
      - Intro: psc/u8intro.md
      - Worksheet: psc/u8ws.md
      - Lab: psc/u8lab.md
      # - Bonus: psc/u8b.md
    - Unit 9 - Certificate and Key Madness:
      - Intro: psc/u9intro.md
      - Worksheet: psc/u9ws.md
      - Lab: psc/u9lab.md
    - Unit 10 - Recap and Final Project:
      - Intro: psc/u10intro.md
      - Worksheet: psc/u10ws.md
      # - Lab: psc/u10lab.md
      # - Bonus: psc/u10b.md
    - Course Resources:
      - External Resources: psc/resources.md
      # - Downloads: psc/downloads.md

  - Linux Automation Course:
    - Course Overview:
      - Syllabus: pcae/syllabus.md
      # - Course Project: pcae/project.md
      - Lab Guide: pcae/lab-guide.md
      - Table of Contents: pcae/unitindex.md
    - Unit 1 - Automation Tools:
      - Intro: pcae/u1intro.md
      - Worksheet: pcae/u1ws.md
      - Lab: pcae/u1lab.md
    - Unit 2 - Interacting with the OS:
      - Intro: pcae/u2intro.md
      - Worksheet: pcae/u2ws.md
      - Lab: pcae/u2lab.md
    - Unit 3 - Creating && Using Inventories:
      - Intro: pcae/u3intro.md
      - Worksheet: pcae/u3ws.md
      - Lab: pcae/u3lab.md
    - Unit 4 - Admin Commands && Ad-Hoc Commands:
      - Intro: pcae/u4intro.md
      - Worksheet: pcae/u4ws.md
      - Lab: pcae/u4lab.md
    - Unit 5 - Environment and Local Variables:
    #   - Intro: pcae/u5intro.md
      - Worksheet: pcae/u5ws.md
      - Lab: pcae/u5lab.md
    - Unit 6 - Automating Docker Builds:
      - Intro: pcae/u6intro.md
      - Worksheet: pcae/u6ws.md
      - Lab: pcae/u6lab.md
    - Unit 7 - Automating Docker Environments:
    #   - Intro: pcae/u7intro.md
      - Worksheet: pcae/u7ws.md
      - Lab: pcae/u7lab.md
    #   - Bonus: pcae/u7b.md
    - Unit 8 - Automating K8s Environments:
      - Intro: pcae/u8intro.md
      - Worksheet: pcae/u8ws.md
      - Lab: pcae/u8lab.md
    #   - Bonus: pcae/u8b.md
    - Unit 9 - Build && Deploy Linux Systems:
      - Intro: pcae/u9intro.md
      - Worksheet: pcae/u9ws.md
      - Lab: pcae/u9lab.md
    - Unit 10 - Harden Linux Systems:
    #   - Intro: pcae/u10intro.md
      - Worksheet: pcae/u10ws.md
      - Lab: pcae/u10lab.md
    # - Unit 11 - Update && Patch Systems:
    #   - Intro: pcae/u11intro.md
    #   - Worksheet: pcae/u11ws.md
    #   - Lab: pcae/u11lab.md
    # - Unit 12 - Configure Network Devices:
    #   - Intro: pcae/u12intro.md
    #   - Worksheet: pcae/u12ws.md
    #   - Lab: pcae/u12lab.md
    # - Unit 13 - Remediating and Reporting on Drift:
    #   - Intro: pcae/u13intro.md
    #   - Worksheet: pcae/u13ws.md
    #   - Lab: pcae/u13lab.md
    # - Unit 14 - CI/CD Pipelines:
    #   - Intro: pcae/u14intro.md
    #   - Worksheet: pcae/u14ws.md
    #   - Lab: pcae/u14lab.md
    # - Unit 15 - Troubleshooting/Testing 1:
    #   - Intro: pcae/u15intro.md
    #   - Worksheet: pcae/u15ws.md
    #   - Lab: pcae/u15lab.md
    # - Unit 16 - Troubleshooting/Testing 2:
    #   - Intro: pcae/u16intro.md
    #   - Worksheet: pcae/u16ws.md
    #   - Lab: pcae/u16lab.md
    - Course Resources:
      - External Resources: pcae/resources.md
      - Downloads: pcae/downloads.md
  - Blog:
    - blog/learning.md


extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/m6VPPD9usw
      name: ProLUG on Discord

    - icon: fontawesome/brands/github
      link: https://github.com/ProfessionalLinuxUsersGroup
      name: ProLUG GitHub Repositories

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@het_tanis8213
      name: \@Het_Tanis Youtube

    - icon: material/web
      link: https://prolug.org/
      name: https://ProLUG.org/

copyright: Copyright &copy; 2026 Professional Linux Users Group

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys

plugins:
  - glightbox
  - search
  - blog
  - to-pdf:
      author: Scott Champine
      copyright: Copyright Â© Professional Linux Users Group 2026
      cover_subtitle: Produced by Scott Champine and ProLUG
      output_path: prolugcoursebooks.pdf
      download_link: header

  # - git-revision-date-localized:
  #     enable_creation_date: true
  # - git-committers:
  #     repository: ProfessionalLinuxUsersGroup/course-books
  #     branch: main

extra_css:
  - stylesheets/extra.css
